version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: BooklogContainer
    environment:
      SA_PASSWORD: "V@icorinthians0508"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - booklog_sql_data:/var/opt/mssql

volumes:
  booklog_sql_data:
